name: Download Spotify
on: [push]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install spotdl
      run: pip install spotdl
    - name: Download playlist
      run: spotdl "https://open.spotify.com/playlist/2d27XbqeTU6ePJVokdgg57" --output "{title}.{output-ext}"
    - uses: actions/upload-artifact@v4
      with:
        name: music
        path: "*.mp3"
