name: Download Spotify
on: [push]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install spotdl
      run: pip install spotdl
    - name: Download playlist
      run: spotdl "https://open.spotify.com/playlist/2d27XbqeTU6ePJVokdgg57?si=Pw481dc3RvatpkI9TfkKvA&pi=F6ucS9xHQDqEH"
    - uses: actions/upload-artifact@v3
      with:
        name: music
        path: "*.mp3"
